### ISSUE TITLE
Got Error  Vue StoreFront Layered Navigation module - in Vuetique theme

### ISSUE THREAD

**Issue by rebinti** [GetNoticedNL/vsf-layered-navigation#1]
![Screenshot from 2019 04 17 15 26 21 png  PNG Image  1920 × 1080 pixels    Scaled  90  ](https://user-images.githubusercontent.com/7974043/56279504-e4b0ff80-6125-11e9-8a2f-4e75f5001092.png)

**Comment by DaanKouters** [comment]
hi @rebinti ,

did you change the onFilterChange method in `src/themes/vuetique/pages/Category.vue` ?

**Comment by janmyszkier** [comment]
@DaanKouters since it's your PR (https://github.com/GetNoticedNL/vsf-layered-navigation/commit/2604b36e61615655d00f5e15d420bb71b764632e) which implemented those into the ReadMe, can you shed some light on why was it suggested to add this line into the template?

**Comment by DaanKouters** [comment]
@janmyszkier as this is the helper function which makes it possible to build the filter query with objects (multiselect) as filters

**Comment by janmyszkier** [comment]
why don't you import it in the vue file that actually uses it then? or was there something else you wanted to add to `Category.vue` that you didn't include in the readme?

**Comment by DaanKouters** [comment]
This is in the readme.
The helper function is used in the onFilterChanged method. This is for now the way to do this. See the ‘core/pages/Category.js’ file, this is the equivalent of ‘buildFilterProductsQuery’ which is imported from core/helpers.

**Comment by DaanKouters** [comment]
@janmyszkier as this was not clear to everyone, i updated the readme for the theme integration part.

**Comment by janmyszkier** [comment]
well,then @rebinti does that solve it for you?

**Comment by rebinti** [comment]
Yes that worked for me but issue in style.
