### ISSUE TITLE
Clicking the priceslider resets the filter

### ISSUE THREAD

**Issue by Jensderond** [GetNoticedNL/vsf-layered-navigation#2]
When clicking the price slider the products change but the filter(UI) doesn't reset. 

![price-changing-issue](https://user-images.githubusercontent.com/6972822/57448064-cb006500-7258-11e9-8486-a58c5fd2b157.gif)

**Comment by DaanKouters** [comment]
Hi, thanks for reporting.
I’ll investigate and come back at it here 👍🏻

**Comment by DaanKouters** [comment]
Hi, thanks for reporting.
I’ll investigate and come back at it here 👍🏻

**Comment by DaanKouters** [comment]
hi @themreza 
thank you for your message. We are working on it in the develop branch and are planning a release in the near future

**Comment by DaanKouters** [comment]
This is now finished in develop, solving some other issues and we are ready for a new release.

**Comment by DaanKouters** [comment]
This is included in the latest release
