### ISSUE TITLE
The property is not deleted from `activeFilters`

### ISSUE THREAD

**Issue by natalia-reyveys** [GetNoticedNL/vsf-layered-navigation#3]
When I choose f.e. some filters from `color2` then I'll have `Object.keys(filters.chosen).length = 1` and have in `color2` array one item, if I delete filter then also `Object.keys(filters.chosen).length = 1`  but   in `color2` array null item.

**Comment by DaanKouters** [comment]
hi @natalia-reyveys 
thank you for adding issue, we discussed it and i'll let you know what i have it finished.

**Comment by DaanKouters** [comment]
@natalia-reyveys this now solved in the hackathon, in the develop branch.
When we finish some other issues we release a new version of the module.

**Comment by DaanKouters** [comment]
This is included in the latest release
