### ISSUE TITLE
Improvement for the Category page example

### ISSUE THREAD

**Issue by dimasch** [GetNoticedNL/vsf-layered-navigation#4]
Hey, @DaanKouters :)

We can improve by use `isServer` helper:

`import { isServer } from '@vue-storefront/core/helpers'` instead 

https://github.com/GetNoticedNL/vsf-layered-navigation/blob/2f97ab58127cb9dc65fa12368acfae1db822c19d/theme-implementation/pages/Category.vue#L49

**Comment by DaanKouters** [comment]
hi @dimasch ,

yes indeed, i'll add this 👍

**Comment by DaanKouters** [comment]
This is included in the latest release
