### ISSUE TITLE
Hide filtering options that would yield 0 results

### ISSUE THREAD

**Issue by benjick** [GetNoticedNL/vsf-layered-navigation#6]
Any plans on adding functionality to hide filter options that would result in an empty search?

For example: I've selected a color and have 10 results, then I can filter by for example size: `Small`, `Large`, `Medium`. If I select `Medium` I would get 0 results, then I want to hide `Medium` from the filter options

**Comment by DaanKouters** [comment]
hi @benjick , yes we can look into this for sure.
This can be achieved with the products left counter part.

**Comment by DaanKouters** [comment]
Also filter options would return in no change in the productlist should be hidden.

**Comment by DaanKouters** [comment]
This is included in the latest release
